### ISSUE TITLE
Trying to write to a file in a dir that doesn't exist freezes neovim

### ISSUE THREAD

**Issue by IndianBoy42** [jghauser/mkdir.nvim#3]
`:w ~/doesntexist/file` or `:e ~/doesntexist/file` will lead to neovim freezing and taking up 100% of one core of my cpu, with no way to stop it

I am using packer with the example use statement from the README.md

**Comment by jghauser** [comment]
Thanks for your feedback! However, I can't reproduce this. Can you give me more information about your setup (OS, neovim version etc.)? A minimal config that causes the error would also be helpful. Thanks!

**Comment by jghauser** [comment]
Closing for lack of response. Please feel free to re-open if you still have the issue.
