### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by XXiaoA** [jghauser/mkdir.nvim#5]
![IMG_20220224_233410](https://user-images.githubusercontent.com/62557596/155555875-3218405f-a598-4f88-a47c-2ba33178b663.jpg)
I have installed it

**Comment by jghauser** [comment]
Hey @XXiaoA ! Thanks for the issue report! Can you tell me exactly what you were doing when the error occurred? Just to make sure, you ran `PackerSync` after the changing your config? What command did you execute that caused the error?

**Comment by XXiaoA** [comment]
> Hey @XXiaoA ! Thanks for the issue report! Can you tell me exactly what you were doing when the error occurred? Just to make sure, you ran `PackerSync` after the changing your config? What command did you execute that caused the error?

@jghauser I just run `PackerInstall` after config it. And it shows it installs successfully. However, when i run `:w 1/1.lua`, it throws an error. `1` is a folder that does not exist .

**Comment by jghauser** [comment]
I'm at a bit of a loss here as this works perfectly on my end. Can you post your config here so I can troubleshoot it? Thanks!

**Comment by XXiaoA** [comment]
[see it here](https://github.com/XXiaoA/neovim-configuration/blob/3ae16684bcc014282539068de030208c8eff0cf6/lua/plugins.lua#L99)

**Comment by XXiaoA** [comment]
I find another plugin instead of this plugin.Anyhow, really thank you.Have a good day😊

**Comment by jghauser** [comment]
I've had a try with your config and it seems for some reason the `autocmd` doesn't get triggered. Do you know if you have anything in your config that might cause that? The folder is created properly when I call the command manually. I'll have a look at this later, it might really be a big!

**Comment by XXiaoA** [comment]
> I've had a try with your config and it seems for some reason the `autocmd` doesn't get triggered. Do you know if you have anything in your config that might cause that? The folder is created properly when I call the command manually. I'll have a look at this later, it might really be a big!

Sorry, i don't know why. It may conflict with other plugins. Thank you.

**Comment by jghauser** [comment]
I think I found the fix! Let me know if it works and if it doesn't please feel free to re-open this issue. :)

**Comment by XXiaoA** [comment]
> I think I found the fix! Let me know if it works and if it doesn't please feel free to re-open this issue. :)

it still doesn't work😂. I have run `PackerUpdate`.
And it seems that i cann't re-open it cuz. it was closed by you.

**Comment by jghauser** [comment]
Ok, I have now figured out what is the issue at least and can replicate it with my own config! The error only happens if you open an existing file and then try to write it to a new location. It doesn't happen with a new buffer that is written for the first time. I'll get back to you once I figure out why this happens!

**Comment by jghauser** [comment]
Alright, now I think I got it! Thanks a lot for reporting this, I somehow didn't think of this use case! :)

**Comment by XXiaoA** [comment]
> Alright, now I think I got it! Thanks a lot for reporting this, I somehow didn't think of this use case! :)

yep，it can work rightly now! i STAR it!😊
So why it was wrong when save it which was created before?
